version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "ci"


  - package-ecosystem: "pnpm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"